#!/usr/bin/env bash

mv $HOME/.zshrc $HOME/.zshrc.bak
mv $HOME/.zshenv $HOME/.zshenv.bak
mv $HOME/.tmux.conf $HOME/.tmux.conf.bak

mv $HOME/.config/zsh $HOME/.config/zsh.bak
mv $HOME/.config/nvim $HOME/.config/nvim.bak
mv $HOME/.config/alacritty $HOME/.config/alacritty.bak
mv $HOME/.config/i3 $HOME/.config/i3.bak


ln -s $HOME/.dotfiles/zshenv $HOME/.zshenv
ln -s $HOME/.dotfiles/tmux.conf $HOME/.tmux.conf

ln -s $HOME/.dotfiles/zsh $HOME/.config/zsh
ln -s $HOME/.dotfiles/nvim $HOME/.config/nvim
ln -s $HOME/.dotfiles/alacritty $HOME/.config/alacritty
ln -s $HOME/.dotfiles/i3 $HOME/.config/i3
