#!/usr/bin/env bash

mv $HOME/.zshrc $HOME/.zshrc.bak
mv $HOME/.zshenv $HOME/.zshenv.bak
mv $HOME/.termux $HOME/.termux.bak

mkdir $HOME/.config

mv $HOME/.config/zsh $HOME/.config/zsh.bak
mv $HOME/.config/nvim $HOME/.config/nvim.bak
mv $HOME/.config/alacritty $HOME/.config/alacritty.bak
mv $HOME/.config/i3 $HOME/.config/i3.bak
mv $HOME/.config/kitty $HOME/.config/kitty.bak
mv $HOME/.config/ranger $HOME/.config/range.bak
mv $HOME/.config/helix $HOME/.config/hel.bak
mv $HOME/.config/tmux $HOME/.config/tmux.bak

ln -s $HOME/.dotfiles/zshenv $HOME/.zshenv
ln -s $HOME/.dotfiles/termux $HOME/.termux

ln -s $HOME/.dotfiles/zsh $HOME/.config/zsh
ln -s $HOME/.dotfiles/nvim $HOME/.config/nvim
ln -s $HOME/.dotfiles/alacritty $HOME/.config/alacritty
ln -s $HOME/.dotfiles/i3 $HOME/.config/i3
ln -s $HOME/.dotfiles/kitty $HOME/.config/kitty
ln -s $HOME/.dotfiles/ranger $HOME/.config/ranger
ln -s $HOME/.dotfiles/helix $HOME/.config/helix
ln -s $HOME/.dotfiles/tmux $HOME/.config/tmux

# locale - emre keyboard
# sudo ln -s $HOME/.dotfiles/locale/tr /usr/share/X11/xkb/symbols/tr               # sudo chmod 644 /usr/share/X11/xkb/symbols/tr # sudo chown root:root /usr/share/X11/xkb/symbols/tr
#sudo ln -s $HOME/.dotfiles/locale/evdev.xml /usr/share/X11/xkb/rules/evdev.xml   # sudo chmod 644 /usr/share/X11/xkb/rules/evdev.xml # sudo chown root:root /usr/share/X11/xkb/rules/evdev.xml
